### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/tasm-lang#22]
Should run all tests and `cargo clippy --all-targets` and probably some other things as well

**Comment by einar-triton** [comment]
Sounds like fun.  I will try mimicking the other repos (TritonVM?) with CI.

**Comment by einar-triton** [comment]
@Sword-Smith: since you asked me directly not to [tie down](https://github.com/TritonVM/tasm-lang/pull/17#issuecomment-1471595353) the dependencies' versions, I need your approval on this one.  I think this is a case, where we have to do it.  If you pull this branch and remove my new version specification for `rand` in `Cargo.toml`, `cargo build` fails due to what seems to be API changes.  If  I understand [Cargo's SemVer](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) correctly, this just puts a lower bound on the dependency version and all newer (and non-API breaking) versions _will be preferred_.
